const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@L&P";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*********";
const retypePassWord = "Retype Password";
const name = "Name";
const nameHint = "Tom Hanks";
const forgetpass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginwith = "Log in with";
const termAndCond = "Terms and Conditions";
const privacyPolicy = "Privacy Policy";
const alreadyHaveAccount = "Already have an account? ";

const home = "Home", categories = "Categories", cart = "Cart", account = "Account";